# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ,components]
  pull_request: {}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: recursive

      # Runs a set of commands using the runners shell
      - name: build deps 
        run: |
          python3 build.py --setup --par=4  -D COPROTO_ENABLE_BOOST=ON -D COPROTO_ENABLE_OPENSSL=ON -DCOPROTO_ASAN=true  -DCMAKE_BUILD_TYPE=RELWITHDEBINFO
          
      - name: build library
        run: |
          python3 build.py --par=4   -DCMAKE_BUILD_TYPE=RELWITHDEBINFO
              
      - name: unit test
        run: |
          ./out/build/linux/frontend/frontend -u
          
      - name: find source tree
        run: |
            cd cmake/testProject
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH=../../
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..
            
      - name: hint test
        run: |
            cd cmake/testProject
            cmake -S . -B out/  -D COPROTO_HINT=../..
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..

      - name: install prefix test
        run: |
            python3 build.py --setup --install=~/install
            python3 build.py --install=~/install
            cd cmake/testProject
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/install
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..
            

      - name: install test
        run: |
            python3 build.py --setup --install --sudo
            python3 build.py --install --sudo
            cd cmake/testProject
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..

  
  # This workflow contains a single job called "build"
  build-osx:
    # The type of runner that the job will run on
    runs-on: macos-latest
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: recursive

      # Runs a set of commands using the runners shell
      - name: build library
        run: |
          python3 build.py  -D COPROTO_ENABLE_BOOST=ON
              
      - name: unit test
        run: |
          ./out/build/osx/frontend/frontend -u
          
      - name: find source tree
        run: |
            cd cmake/testProject
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH=../../
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..
            
      - name: hint test
        run: |
            cd cmake/testProject
            cmake -S . -B out/  -D COPROTO_HINT=../..
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..

      - name: install prefix test
        run: |
            python3 build.py --install=~/install
            cd cmake/testProject
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/install
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..
            

      - name: install test
        run: |
            python3 build.py --install --sudo
            cd cmake/testProject
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release
            cmake --build out/
            ./out/main
            rm -rf out/
            cd ../..

  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-2019
    timeout-minutes: 20
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: ilammy/msvc-dev-cmd@v1


      # Runs a set of commands using the runners shell
      - name: build library
        run: |
          python3 build.py -G Ninja  -D COPROTO_ENABLE_BOOST=ON
      
      - name: unit test
        run: |
          ./out/build/x64-Release/frontend/frontend.exe -u
          
      - name: find source tree
        run: |
            cd cmake/testProject
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH=../../
            cmake --build out/ --config Release
            ./out/Release/main.exe
            rm -r -fo out/
            cd ../..
            
      - name: hint test
        run: |
            python3 build.py
            cd cmake/testProject
            cmake -S . -B out/  -D COPROTO_HINT=../..
            cmake --build out/ --config Release
            ./out/Release/main.exe
            rm -r -fo out/
            cd ../..

      - name: install prefix test
        run: |
            python3 build.py --install=~/install 
            cd cmake/testProject
            cmake -S . -B out/  -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/install
            cmake --build out/ --config Release
            ./out/Release/main.exe
            rm -r -fo out/
            cd ../..
